SLURM_JOBID=319604
SLURM_JOB_NODELIST=cs-cpu-01
something
Counter({0: 1429388, 1: 26660})
Counter({0: 1426891, 1: 29157})
HospID_Reop_CABG                0
HospID_total_CABG               0
surgyear                        0
HospID_total_cardiac_surgery    0
surgid_total_cardiac_surgery    0
                               ..
NumDisV_ordinal                 0
LeftMain                        0
EF_less_equal_35                0
BMI                             0
Reoperation                     0
Length: 61, dtype: int64
0
test
/home/yaararum/Files/model_outputs/grid search stsrcom with experience scale pos.txt
exception calling callback for <Future at 0x7f1de403cd50 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 359, in __call__
    self.parallel.dispatch_next()
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 792, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 178, in submit
    fn, *args, **kwargs)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1102, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
Traceback (most recent call last):
  File "stsrcommodel.py", line 222, in <module>
    choose_script(args.model)
  File "stsrcommodel.py", line 201, in choose_script
    hyper_paramytize_optimization(f)
  File "stsrcommodel.py", line 102, in hyper_paramytize_optimization
    grid_result = grid.fit(X, y)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 841, in fit
    self._run_search(evaluate_candidates)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 1296, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 809, in evaluate_candidates
    enumerate(cv.split(X, y, groups))))
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 359, in __call__
    self.parallel.dispatch_next()
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 792, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 178, in submit
    fn, *args, **kwargs)
  File "/home/yaararum/.conda/envs/yaara_env/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1102, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
slurmstepd: error: Detected 469 oom-kill event(s) in step 319604.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
